### PR TITLE
Switch from xz to zstd

### PR DESCRIPTION
**Pull request by androm3da**

### CODE REVIEW

**Comment by androm3da** [comment]
Do we want to change from `xz` or is that overkill?

**Comment by quic-mathbern** [comment]
I'd say the change is benign, so why not? :)

**Review by quic-mathbern — APPROVED** [review]

**Comment by androm3da** [comment]
I think this change would be a benefit to anyone who has to decompress these rootfs tarballs.  QEMU `check-functional` for example.

`xz` decompression is quite a bit slower than `zstd`.

**Comment by androm3da** [comment]
Resulting archives are larger than the ones compressed with `xz` -- as expected.   But it's quite a big difference for those statically linked toolchains.  

```
-rw-r--r-- 1 bcain users 952M Nov  1 02:45 clang+llvm-19.1.2-cross-hexagon-unknown-linux-musl.tar.zst
-rw-r--r-- 1 bcain users 1.6G Nov  1 02:46 clang+llvm-19.1.2-cross-hexagon-unknown-linux-musl_aarch64-windows-gnu.tar.zst
-rw-r--r-- 1 bcain users 1.7G Nov  1 02:46 clang+llvm-19.1.2-cross-hexagon-unknown-linux-musl_x86_64-windows-gnu.tar.zst
-rw-r--r-- 1 bcain users 8.5G Nov  1 02:48 clang+llvm-19.1.2-cross-hexagon-unknown-linux-musl_x86_64-linux-musl.tar.zst
-rw-r--r-- 1 bcain users 8.6G Nov  1 02:51 clang+llvm-19.1.2-cross-hexagon-unknown-linux-musl_aarch64-linux-gnu.tar.zst
```

compare w/the previous ones w/xz:

```
clang+llvm-19.1.2-cross-hexagon-unknown-linux-musl.tar.xz 664.4 MB
clang+llvm-19.1.2-cross-hexagon-unknown-linux-musl_aarch64-windows-gnu.tar.xz 1023.0 MB
clang+llvm-19.1.2-cross-hexagon-unknown-linux-musl_x86_64-windows-gnu.tar.xz 1.1 GB
clang+llvm-19.1.2-cross-hexagon-unknown-linux-musl_x86_64-linux-musl.tar.xz 5.9 GB
clang+llvm-19.1.2-cross-hexagon-unknown-linux-musl_aarch64-linux-gnu.tar.xz 5.8 GB
```

I guess we'll keep it w/the `zstd` compression until we encounter problems caused by the disk space used.

**Pull request merged**
